2018-12-19 13:16:50 jdbc[10]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at main.java.Database.connect(Database.java:97)
	at main.java.controllers.SearchController$5.call(SearchController.java:314)
	at main.java.controllers.SearchController$5.call(SearchController.java:299)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 17 more
2018-12-19 13:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-197]
2018-12-19 13:25:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-197]
2018-12-19 13:26:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-197]
2018-12-19 13:26:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-197]
2018-12-19 13:26:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-197]
2018-12-19 13:26:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-197]
